export const slotsWords = [
  "Cyclop Smash",
  "Hand of midas",
  "Bonanza xmas",
  "Beast Below",
  "Фрутка",
  "Sweet Bonanza 1000",
  "Wisdom of Athena",
  "Дуэльки",
  "rip city",
  "Собаки Мегавейс",
  "Olympus super scatter",
  "Бонанза",
  "Sugar Rush",
  "Hot Pepper",
  "Gates of Olympus",
  "starlight princess 1000",
  "Mermaid's Treasure Trove",
  "Фрутка 2",
  "Lucky Farm Bonanza",
  "Stormforged",
  "Sweet Bonanza Dice",
  "sweet bonanza",
  "Бонанза топовая",
  "Cyber wolf",
  "Sweet Rush Bonanza",
  "Wisdom of Athena 1000",
  "Evil eyes",
  "Starlight Princess",
  "фрут пати",
  "Rabbir Garden",
  "Champions of rome",
  "Wild beach party",
  "Florageddon",
  "Gates of hades",
  "Sweet Bonanza",
  "Dork unit",
  "sweet bonanza 1000",
  "Баназа обычная",
  "Jewel rush",
  "Бонанза зимняя",
  "Rooster fury",
  "in jazz",
  "Gates of Olympus 1000",
  "Фрутка",
  "Extra juicy megaways",
  "Carnival bonanza",
  "Свит бананза",
  "Wanted",
  "Olympus",
  "beam boys",
  "Биг басс 1000",
  "Sweet Rush Bonanza",
  "Wild Beach Party",
  "Evil Eyes",
  "Gates of Hades",
  "Florageddon",
  "Sugar Rush",
  "Beast Below",
  "Cyclop Smash",
  "Hot Pepper",
  "Бонанза обычная",
  "Gates of Olympus",
  "Sweet Bonanza Dice",
  "Sweet Bonanza",
  "Дуэльки",
  "Starlight Princess",
  "Фрутка 2",
  "Bonanza xmas",
  "Wisdom of Athena",
  "Sweet Bonanza 1000",
  "Rooster fury",
  "Hand of midas",
  "Rabbir Garden",
  "Бонанза",
  "Sweet Bonanza Dice",
  "Olympus super scatter",
  "Wild beach party",
  "Cyber wolf",
  "Lucky Farm Bonanza",
  "Beast Below",
  "Фрутка",
  "Rip city",
  "Dork unit",
  "Champions of rome",
  "Фрут пати",
  "Mermaid's Treasure Trove",
  "Hot Pepper",
  "Gates of Olympus 1000",
  "Бонанза топовая",
  "Evil eyes",
  "Sweet Rush Bonanza",
  "Stormforged",
  "Florageddon",
  "Wanted",
  "Wisdom of Athena 1000",
  "Sweet bonanza",
  "Cyclop Smash",
  "Биг басс 1000",
  "Olympus",
  "beam boys",
  "in jazz",
  "Carnival bonanza",
];
